algoritmo "apto para carteira de motorista"
var
idade: inteiro
nasc: inteiro
ano_At:inteiro 
inicio
    escreval("TESTE PARA CARTEIRA ")
    escreval("quando vc nasceu?")
        leia(nasc)
    escreval("qual o ano atual? ")
        leia(ano_At)
    idade<- ano_AT- nasc 
        se (IDADE>=18)ENTAO 
            escreval("APTO") 
        SENAO 
            escreval("INAPTO")
        FIMSE

fimalgoritmo