algoritmo "meu nome "
var
 nome: caractere
 idade: real
 trabalho: caractere
 area: caractere
inicio
escreva("escreva seu nome")
leia(nome)
escreva ( " muito prazer " , nome )
escreva( " qual a sua idade? ")
leia(idade)
escreva(  "muito prazer"  ,  nome  , "incrivel vc ter", idade, " anos ")
 escreva ("onde vc trabalha?")
 leia(trabalho)
 escreva( "muito legal qual a sua área?")
 leia (area)
 escreva (" muito legal espero que vc goste de trabalhar na" , area)
fimalgoritmo